Release action overhaul: run on demand

diff --git a/.github/workflows/plugin-release-ci.yml b/.github/workflows/plugin-release-ci.yml
--- a/.github/workflows/plugin-release-ci.yml
+++ b/.github/workflows/plugin-release-ci.yml
@@ -2,11 +2,11 @@
 name: Release Plugin
 
 on:
-  push:
-    tags:
-    - v[0-9]+.[0-9]+.[0-9]+
-    - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
-    - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
+  workflow_dispatch:
+    inputs:
+      version:
+        type: string
+        description: Version to release
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
@@ -15,54 +15,100 @@ concurrency:
 env:
   GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
 
+permissions: {}
+
 jobs:
-  publish:
-    name: Publish release
+  pre-release-check:
+    permissions:
+      contents: read
+    name: Pre-release check
     runs-on: ubuntu-latest
     environment: production
     steps:
+    - name: Version check
+      run: |
+        if ! [[ ${{ inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(rc|alpha|beta)[0-9]+)?$ ]]; then
+          echo "[ERROR]: Input version doesn't follow semver:" ${{ inputs.version }}
+          exit 1
+        fi
     - name: Checkout
       uses: actions/checkout@v6
-      with:
-        fetch-depth: 0
     - name: Install JDK 17
       uses: actions/setup-java@v5
       with:
         distribution: temurin
         java-version: 17
         cache: gradle
+    - name: Setup Gradle
+      uses: gradle/actions/setup-gradle@v5
     - name: Build project
-      run: ./gradlew build --no-daemon  -Porg.jsonschema2dataclass.internal.git-version=true
-      env:
-        VERSION: ${{ github.ref }}
-    - name: Find Tag
-      id: tagger
-      uses: jimschubert/query-tag-action@v2
-      with:
-        skip-unshallow: 'true'
-        commit-ish: HEAD
+      run: >-
+        ./gradlew build --no-daemon
+        -Porg.jsonschema2dataclass.internal.git-version-override=${{ inputs.version }}
+  publish-github:
+    permissions:
+      contents: write
+    name: Publish GitHub
+    runs-on: ubuntu-latest
+    environment: production
+    needs:
+    - pre-release-check
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v6
+
     - name: Create Github release
       run: |
         PRE_RELEASE=""
-        if [[ ${{steps.tagger.outputs.tag}} == *"beta"* ]]; then
+        if [[ ${{ inputs.version }} == *"beta"* ]]; then
           PRE_RELEASE="-p"
         fi
-        if [[ ${{steps.tagger.outputs.tag}} == *"alpha"* ]]; then
+        if [[ ${{ inputs.version }} == *"alpha"* ]]; then
           PRE_RELEASE="-p"
         fi
-        if [[ ${{steps.tagger.outputs.tag}} == *"rc"* ]]; then
+        if [[ ${{ inputs.version }} == *"rc"* ]]; then
           PRE_RELEASE="-p"
         fi
+
         set -x
-        hub release create $PRE_RELEASE -m "${{steps.tagger.outputs.tag}}" "${{steps.tagger.outputs.tag}}"
+        gh release create --draft $PRE_RELEASE "v${{ inputs.version }}" --fail-on-no-commits --generate-notes
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        VERSION: ${{steps.tagger.outputs.tag}}
-    - name: Publish
-      uses: burrunan/gradle-cache-action@v3.0
+  publish-gradle:
+    needs:
+    - publish-github
+    permissions:
+      contents: read
+    runs-on: ubuntu-latest
+    environment: production
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v6
+    - name: Install JDK 17
+      uses: actions/setup-java@v5
       with:
-        remote-build-cache-proxy-enabled: false
-        properties: |
-          gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
-          gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
-        arguments: publishPlugins -s --scan --no-daemon
+        distribution: temurin
+        java-version: 17
+        cache: gradle
+    - name: Setup Gradle
+      uses: gradle/actions/setup-gradle@v5
+    - name: Publish
+      run: >-
+        ./gradlew publishPlugins -s --scan --no-daemon
+        -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
+        -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
+  finalise-github-release:
+    needs:
+    - publish-gradle
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    environment: production
+    steps:
+    - name: Checkout repo
+      uses: actions/checkout@v6
+    - name: Finalise Github release
+      run: |
+        gh release edit "v${{ inputs.version }}" --draft=false
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
