run some secret checks before publishing

diff --git a/.github/workflows/plugin-release-ci.yml b/.github/workflows/plugin-release-ci.yml
--- a/.github/workflows/plugin-release-ci.yml
+++ b/.github/workflows/plugin-release-ci.yml
@@ -102,10 +102,26 @@ jobs:
         java-version: 17
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v5
+    - name: Validate
+      run: |
+        if [[ -z "$GRADLE_PUBLISH_KEY" -or -z "$GRADLE_PUBLISH_SECRET" ]]; then
+          echo '[ERROR] no secrets passed'
+          exit 1
+        fi
+        if echo "$GRADLE_PUBLISH_KEY$GRADLE_PUBLISH_SECRET" | grep ' ' >/dev/null 2>/dev/null; then
+          echo '[ERROR] invalid symbols in secrets'
+        fi
+
+        ./gradlew publishPlugins -s --scan --no-daemon --no-configuration-cache --validate-only \
+          -Porg.jsonschema2dataclass.internal.git-version-override=$PLUGIN_VERSION
+      env:
+        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_SECRET }}
+        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
+        PLUGIN_VERSION: ${{ inputs.version }}
     - name: Publish
-      run: >-
-        ./gradlew publishPlugins -s --scan --no-daemon
-        "-Porg.jsonschema2dataclass.internal.git-version-override=$PLUGIN_VERSION"
+      run: |
+        ./gradlew publishPlugins -s --scan --no-daemon --no-configuration-cache \
+          -Porg.jsonschema2dataclass.internal.git-version-override=$PLUGIN_VERSION
       env:
         GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_SECRET }}
         GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
